global:
  scrape_interval: 15s # How frequently to scrape targets.
  evaluation_interval: 15s # How frequently to evaluate rules.

scrape_configs:
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:5001'] # Docker Compose service name and internal port

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:5002']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:5003']

  - job_name: 'prometheus' # To scrape Prometheus itself
    static_configs:
      - targets: ['prometheus:9090']  # Changed from localhost to service name

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
      
  